apiVersion: v1
kind: Service
metadata:
  name: backend-proxy
spec:
  type: LoadBalancer
  selector:
    app: backend-proxy
  ports:
  - name: https
    protocol: TCP 
    port: 443
    targetPort: 443